[package]
name = "aaa"
version = "1.1.1"
edition = "2018"
authors = ["DomesticMoth"]
description = "CLI tool for work with 3a files"
repository = "https://github.com/DomesticMoth/aaa"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
crossterm = "0.22"
rs3a = "1"
clap = { version = "3.1.6", features = ["derive"] }
exitcode = "1.1.2"
